server:
  url: http://localhost
  name: my-server
  port: 8080
  workers: 2
  queue_size: 5
  token_rate: 2
  token_limit: 5

prometheus:
  metrics_port: 9090
  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  scrape_configs:
    - job_name: "tcpie-app"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["localhost:8080"]
